language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=">=1.6,<1.7"
  - DJANGO_VERSION=">=1.7,<1.8"
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
matrix:
    exclude:
        # Python 3.5 does not work with some django versions.
        - python: "3.5"
          env: DJANGO_VERSION=">=1.6,<1.7"
        - python: "3.5"
          env: DJANGO_VERSION=">=1.7,<1.8"
        # Django 1.9 and Python 3.3 don't work together.
        - python: "3.2"
          env: DJANGO_VERSION=">=1.9,<1.10"

install:
  - pip install "Django${DJANGO_VERSION}"
  - pip install .
script:
  - cd $TRAVIS_BUILD_DIR/example-project; python manage.py test djangoplugins
