language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - cd $TRAVIS_BUILD_DIR/example-project; python manage.py test djangoplugins
